export const TASK_REQUEST = "TASK_REQUEST"
export const TASK_REQUEST_FAIL = "TASK_REQUEST_FAIL"


export const POST_REQUEST_SUCCESS = "POST_REQUEST_SUCCESS"

export const UPDATE_REQUEST_SUCCESS = "UPDATE_REQUEST_SUCCESS"


export const DELETE_REQUEST_SUCCESS = "DELELTE_REQUEST_SUCCESS"


export const GET_REQUEST_SUCCESS = "GET_REQUEST_SUCCESS"